name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: convert
      run: shc -T -f k8c.sh
    - name: package
      run: tar -zf k8c
    - name: check
      run: ls -l k8c*
